use QLGT
go
create proc SP_TINHTRANGINSERT
@ID NVARCHAR(20),
@DANHAN BIT,
@HOANTHANH BIT

AS
BEGIN
	IF NOT EXISTS(SELECT * FROM TINHTRANGVUVIEC WHERE @ID = INFORMID)
		BEGIN
			INSERT INTO TINHTRANGVUVIEC VALUES(@ID,@DANHAN,@HOANTHANH)
		END		
			
	ELSE
		PRINT 'SU VIEC DA TON TAI'
END
go
create proc SP_USERSINSERT
@HOTEN NVARCHAR(20),
@USERID NVARCHAR(20),
@USERNAME NVARCHAR(20),
		@SDT VARCHAR(20),
		@DIACHI NVARCHAR(50),
		@CMND NVARCHAR(20),
		@MATKHAU NVARCHAR(20),
		@LOAI INT
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM USERS WHERE CMND = @CMND)
		BEGIN
			IF NOT EXISTS(SELECT * FROM USERS WHERE SDT = @SDT)
				BEGIN
					INSERT INTO USERS(USERID,USERNAME,MK,HOTEN,SDT,CMND,DIACHI,LOAI) VALUES(@USERID,@USERNAME,@MATKHAU,@HOTEN,
					@SDT,
					@CMND,
					@DIACHI,
					@LOAI)
				END
			ELSE
				PRINT'SDT DA TON TAI'
		END
	ELSE
		PRINT 'CMND DA TON TAI'
END